### ISSUE TITLE
Customizing "Add" button.

### ISSUE THREAD

**Issue by SalahAdDin** [CultureHQ/add-to-calendar#300]
Hi, do you have any plan to avoid enable a way to customize the "add" button?

Thanks,

**Comment by kddeisz** [comment]
Hi @SalahAdDin - so you can currently pass whatever you like into the children of the component and that's what will get displayed. You can also override any of the styles (they're listed in https://github.com/CultureHQ/add-to-calendar/blob/master/src/styles.css). Is there some other kind of customization you're talking about or does that take care of it for you?
