### ISSUE TITLE
Interacting with the button is not toggling the drop down menu?

### ISSUE THREAD

**Issue by JPedrys** [CultureHQ/add-to-calendar#480]
Hello, 

I have been trying to use this add to calendar button component for awhile now and I haven't been able to get the drop down menu to toggle by clicking the event button. I even tried importing the styles to see if that resolved my issue and still no luck. If I set the open prop to true the drop down buttons do appear by default and they are functional, but that is the only way I can get them to toggle. Does anyone know what I could possibly be missing? Also is there any straightforward way that I could just cut out the outlook ICS download portion into a function and use that on my own button if I am unable to get this drop down toggle to work?

Any help would be greatly appreciated, thanks!

**Comment by soukiassianb** [comment]
Having the same toggling issue with an electron app. Did you find a solution? Thanks
